{
 "title": "ExplorViz Services",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (up{job=~\".*-service\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Percentage of CPU usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (process_cpu_usage)",
     "legendFormat": "{{job}}"
    },
    { "expr": "sum(process_cpu_usage)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes)",
     "legendFormat": "{{job}}"
    },
    { "expr": "sum (jvm_memory_used_bytes)", "legendFormat": "Total" }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Record Consumption Rate",
   "type": "timeseries",
   "description": "Average number of records consumed per second (per service and topic)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, topic) (kafka_consumer_fetch_manager_records_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"})",
     "legendFormat": "{{job}} ({{topic}})"
    },
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"}",
     "legendFormat": "{{job}}:{{instance}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Byte Consumption Rate",
   "type": "timeseries",
   "description": "Average bytes consumed per second (per service and topic)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, topic) (kafka_consumer_fetch_manager_bytes_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"})",
     "legendFormat": "{{job}} ({{topic}})"
    },
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"}",
     "legendFormat": "{{job}}:{{instance}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Record Dropped Total (per instance and thread)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, thread_id, instance) (kafka_stream_task_dropped_records_total)",
     "legendFormat": "{{instance}}/{{thread_id}}"
    }
   ]
  },
  {
   "title": "Record Dropped Rate (per instance and thread)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, thread_id, instance) (kafka_stream_task_dropped_records_rate)",
     "legendFormat": "{{instance}}/{{thread_id}}"
    }
   ]
  },
  {
   "title": "Consumer Lag (per instance & topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(group, member_host, topic) (kafka_consumergroup_group_lag{topic!=\"token-events\"})",
     "legendFormat": "{{group}} {{member_host}} : {{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Lag (per group & topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(group, topic) (kafka_consumergroup_group_lag{topic!=\"token-events\"})",
     "legendFormat": "{{group}} : {{topic}}"
    }
   ]
  },
  {
   "title": "Record E2E Latency (avg.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance, rocksdb_state_id, rocksdb_window_state_id, thread_id) (kafka_stream_state_record_e2e_latency_avg)",
     "legendFormat": "{{instance}}/{{rocksdb_state_id}}{{rocksdb_window_state_id}}/{{thread_id}}"
    }
   ]
  },
  {
   "title": "Processing Latency per Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_process_latency_avg",
     "legendFormat": "{{job}}/{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average HTTP Response TIme (Success)",
     "type": "timeseries",
     "description": "Average time it took the server to respond to a request to a certain url. Only shows successful requests.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{uri!~\"/q.*|/metrics/\", job=~\"landscape-service|trace-service\", outcome = \"SUCCESS\"}[5m]) ",
       "legendFormat": "{{uri}} ({{job}})"
      }
     ]
    },
    {
     "title": "Total HTTP Requests",
     "type": "stat",
     "description": "Inbound requests per service. Includes scraping by prometheus.",
     "gridPos": { "h": 6, "w": 19, "x": 0, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "round(sum by(job) ((increase(http_server_requests_seconds_count{uri!~\"/q.*|/metrics/\", outcome != \"REDIRECTION\"}[$__range]))))",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "HTTP Outcomes",
     "type": "stat",
     "description": "Inbound requests per service. Includes scraping by prometheus.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(job, outcome)\n (round(increase(http_server_requests_seconds_count{uri!~\"/q.*|/metrics/\", outcome != \"REDIRECTION\"}[$__range])))",
       "legendFormat": "{{job}} {{outcome}}"
      }
     ]
    }
   ]
  }
 ]
}