{
 "title": "User-Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job) (up{job=~\"user-service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Token Events",
   "type": "stat",
   "description": "Token Event sent by the user service and received by the others.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (round(increase(kafka_consumer_fetch_manager_records_consumed_total{topic=\"token-events\"}[$__range])))",
     "legendFormat": "{{job}} received"
    },
    {
     "expr": "sum by(job) (round(increase(kafka_producer_topic_record_send_total{topic=\"token-events\"}[$__range])))",
     "legendFormat": "{{job}} sent"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "description": "Inbound requests per service. Includes scraping by prometheus.",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"user-service\", uri!~\"/q.*\", outcome != \"REDIRECTION\"}",
     "legendFormat": "instance: {{instance}}, URI: {{uri}}, Method: {{method}}, HTTP Status: {{status}}"
    }
   ]
  }
 ]
}